### ISSUE TITLE
Language specific guide does not work

### ISSUE THREAD

**Issue by felixjung** [atom/wrap-guide#21]
Hi,

I'm sorry, but I can't get this to work at all. Copying your example from the documentation and editing it, so that julia files are recognised, the package still uses the global `preferredLineLength` setting instead of what I set in the config.

Here's what I've put in my `config.cson`

``` cson
'wrap-guide':
  'columns': [
    {
      'pattern': '.jl$'
      'column': 100
    }
  ]
```

What am I doing wrong?

**Comment by morenoh149** [comment]
@lee-dohm you're config.cson has probably changed since you posted it. I don't see you set columns by filetype. Have you enabled this in a different way now? Still struggling here to get 80 columns in js but 119 in python and Go.
