### ISSUE TITLE
wrap guide not appearing on Mac OS X

### ISSUE THREAD

**Issue by messuti-edd** [atom/wrap-guide#46]
The wrap guide just doesn't render for me, I'm new to Atom and it took me some time to realize it never rendered from the start, I've verified the configurations:

`Preferred Line Length` is on its default 80

I've tried disabling all the packages I've installed, also starting atom on safe mode, still no wrap guide.

OS: Mac OS X Yosemite 10.10.5
Atom version: 1.0.19 (latest as of writing this)
Checked for console errors: none
Checked in the DOM, the element with the class `.wrap-guide` does exist, it's just not been rendered properly, can't figure out why.

![screen shot 2015-09-30 at 22 17 20](https://cloud.githubusercontent.com/assets/690443/10211443/5adbaaa0-67c1-11e5-83c6-db26889bce71.png)

Am I'm missing something perhaps?

**Comment by dmose** [comment]
I'm seeing this too.

**Comment by dmose** [comment]
In my case, it turned out that the ::shadow pseudo CSS selector was not firing.  After I checked the "Use Shadow DOM" in the Editor section of the Settings pane and restarted, things behaved properly.

**Comment by messuti-edd** [comment]
Yes! that was it, thanks a lot @dmose! I suppose I must have disabled that by accident

**Comment by dmose** [comment]
:-)

**Comment by baziliolg** [comment]
I properly envy you gentlemen who can identify the real source of a problem.

I spent an hour trying to understand why the vertical guide does not show on Mac and on Windows. I reversed the 'disable vertical line in Atom' instruction manuals, but with no effect.
What is this shadow dom switch, and why does it disable the vertical line?

**Comment by gabriel** [comment]
![2016-05-06 at 11 21 am](https://cloud.githubusercontent.com/assets/2669/15082478/c7ac2bfc-137c-11e6-8f83-3e02f0c5c3f7.png)

It says shadow dom option is going away soon, so it might be a real issue...

**Comment by ylansegal** [comment]
`Use Shadow DOM` no longer shows in Atom. I am using `1.12.6`

**Comment by 50Wliu** [comment]
Shadow DOM is going away in Atom 1.13, so this should no longer be an issue.

**Comment by ylansegal** [comment]
@50Wliu This is still a problem for me: The wrap-guide doesn't show in `1.12.6` and I can't use the workarounds anymore.

**Comment by 50Wliu** [comment]
Yes, that's why I specifically referenced 1.13 and not 1.12. All packages relying on the shadow DOM have been reworked.

**Comment by Undistraction** [comment]
I'm seeing this too in 1.13.0 x64 on OSX 10.11.6
