### ISSUE TITLE
Ability to add multiple markers

### ISSUE THREAD

**Issue by stylemistake** [atom/wrap-guide#48]
Here's a picture of how it looks:

![image](https://cloud.githubusercontent.com/assets/1516236/10258837/9ce3c0ae-696a-11e5-8768-f5a5f6c4e13d.png)

In Sublime Text 3, you'd just add these settings:

``` json
{
	"rulers": [ 80, 120 ],
}
```

Sometimes you need to see both rulers in a project (e.g. 80 is the recommended length, but 120 is the hard cap)

**Comment by benogle** [comment]
Closing in favor of #14
