### ISSUE TITLE
The vertical line is displayed at the second column and ignoring the preferredLineLength

### ISSUE THREAD

**Issue by jonaswjs** [atom/wrap-guide#53]
My `preferredLineLength` is 110. I tested and disabled all other community packages but it didn't changed that the line is displayed on the wrong place.

My configuration is here:
https://gist.github.com/jonaswjs/347d62796543e806a07d

I disabled wrap-guide now. But I would like that atom is displayed the line on the right place.

**Comment by lee-dohm** [comment]
Can you show a screenshot of what you're seeing? Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by jonaswjs** [comment]
I'm using `atom 1.5.4` on a `Debian Linux 8`.
I have the same error when starting atom with `atom --safe`.

The configured tab length is 3 and preferred line length is 110 but the vertical line is between the second and third character.

![atom_wrap-guide](https://cloud.githubusercontent.com/assets/7384813/13567753/5db2c9a2-e45d-11e5-9315-bb1ba8ca6963.png)

I didn't followed all the suggestions in the Debugging document.

**Comment by lee-dohm** [comment]
Can you post the contents of your `config.cson` here?

**Comment by jonaswjs** [comment]
My `config.cson` (changed some values to ***):
```JSON
"*":
  core:
    automaticallyUpdate: false
    themes: [
      "one-light-ui"
      "one-light-syntax"
    ]
  editor:
    invisibles: {}
    preferredLineLength: 110
    scrollSensitivity: 110
    tabLength: 3
    tabType: "soft"
  "exception-reporting":
    userId: "***"
  "js-hyperclick": {}
  "linter-jshint":
    disableWhenNoJshintrcFileInPath: true
    lintInlineJavaScript: true
  minimap:
    plugins:
      "find-and-replace": true
      "find-and-replaceDecorationsZIndex": 0
      "highlight-selected": true
      "highlight-selectedDecorationsZIndex": 0
      linter: true
      linterDecorationsZIndex: 0
  "sync-settings":
    _analyticsUserId: "***"
    _lastBackupHash: "***"
    gistId: "347d62796543e806a07d"
    personalAccessToken: "***"
  welcome:
    showOnStartup: false
  whitespace:
    ignoreWhitespaceOnCurrentLine: false
".js.regexp.replacement.source":
  editor:
    preferredLineLength: 2
".js.regexp.source":
  editor:
    preferredLineLength: 2
".js.source":
  editor:
    preferredLineLength: 2
    tabLength: 3
".json.source":
  editor:
    preferredLineLength: 2
    tabLength: 3
```

**Comment by 50Wliu** [comment]
@jonaswjs Somehow you or a package put some scoped settings for `preferredLineLength` for the grammars listed at the bottom of the file.  If you delete those the issue should fix itself.

**Comment by jonaswjs** [comment]
Thank you! I deleted the lines from the `conf.cson` and the vertical line is on the right place now. 

I don't know which package put these settings to the file.

**Comment by JosephTLyons** [comment]
I'm having the same issues, can someone explain how to open the config.cson file specific to the wrap package?

**Comment by 50Wliu** [comment]
@JosephTLyons `~/.atom/config.cson` or `%USERPROFILE%\.atom\config.cson` on Windows.  You can also open it from the Atom menu on macOS, File on Windows, and Edit on Linux.

**Comment by JosephTLyons** [comment]
@50Wliu, thats actually what I did, but I had nothing in that config file related to the wrap package.  My column guide line is way off from the correct position.

**Comment by florianb** [comment]
@JosephTLyons, you might like to check if any third party packages like atom-editorconfig interfere your settings.

**Comment by JosephTLyons** [comment]
I’m trying to do this, but it’s hard when I have many packages.  Not even sure where to begin

**Comment by florianb** [comment]
No worries - a first step could be to post a list of your community-packages (listed by `apm list`)

**Comment by JosephTLyons** [comment]
Here is a list generated by the ls -l command in my .atom/packages folder:

drwxr-xr-x  26 josephlyons  staff   884 Oct  4 02:26 Hydrogen
-rw-r--r--   1 josephlyons  staff    60 Aug 28  2016 README.md
drwxr-xr-x  14 josephlyons  staff   476 Jul 25 00:38 aligner
drwxr-xr-x   6 josephlyons  staff   204 Aug  6 22:23 aligner-javascript
drwxr-xr-x  11 josephlyons  staff   374 Mar  6  2017 ariake-dark-syntax
drwxr-xr-x  33 josephlyons  staff  1122 Aug 14 18:34 atom-beautify
drwxr-xr-x  11 josephlyons  staff   374 Sep  6 16:59 atom-html-preview
drwxr-xr-x  14 josephlyons  staff   476 Oct  4 02:21 atom-ide-ui
drwxr-xr-x  17 josephlyons  staff   578 May 22 15:36 atom-material-ui
drwxr-xr-x  13 josephlyons  staff   442 Oct  5 19:50 auto-copyright
drwxr-xr-x  10 josephlyons  staff   340 Mar  6  2017 autoclose-html
drwxr-xr-x  13 josephlyons  staff   442 Sep 18 16:10 autocomplete-python
drwxr-xr-x  17 josephlyons  staff   578 Aug 30 14:58 busy-signal
drwxr-xr-x  11 josephlyons  staff   374 Mar  6  2017 color-picker
drwxr-xr-x  12 josephlyons  staff   408 Jul 25 00:39 docblockr
drwxr-xr-x  16 josephlyons  staff   544 Sep 20 15:04 file-icons
drwxr-xr-x  14 josephlyons  staff   476 Mar 27  2017 git-time-machine
drwxr-xr-x  14 josephlyons  staff   476 Jul 25 00:39 goto-definition
drwxr-xr-x  10 josephlyons  staff   340 May 21 06:04 hey-pane
drwxr-xr-x  17 josephlyons  staff   578 Mar 25  2017 highlight-selected
drwxr-xr-x  10 josephlyons  staff   340 Sep 13 16:23 ide-csharp
drwxr-xr-x  13 josephlyons  staff   442 Oct  4 18:23 ide-java
drwxr-xr-x  14 josephlyons  staff   476 Oct  4 18:23 ide-php
drwxr-xr-x  21 josephlyons  staff   714 Sep 18 16:10 minimap
drwxr-xr-x  12 josephlyons  staff   408 Oct  5 19:52 minimap-autohider
drwxr-xr-x  11 josephlyons  staff   374 Mar  6  2017 multi-cursor
lrwxr-xr-x   1 josephlyons  staff    36 Mar 28  2017 my-package -> /Users/josephlyons/github/my-package
drwxr-xr-x  10 josephlyons  staff   340 Jun 12 08:27 pdf-view
drwxr-xr-x  17 josephlyons  staff   578 Aug 14 18:37 pigments
drwxr-xr-x  18 josephlyons  staff   612 May 30 22:59 project-manager
drwxr-xr-x  15 josephlyons  staff   510 Aug 30 04:44 sync-settings
drwxr-xr-x  13 josephlyons  staff   442 Oct  4 01:57 zentabs
