### ISSUE TITLE
Broken Pictures

### ISSUE THREAD

**Issue by evanzhu2013** [atom/wrap-guide#54]
<img width="303" alt="2016-04-24 23 45 06" src="https://cloud.githubusercontent.com/assets/7533756/14768499/ad170ab4-0a76-11e6-8889-22093758a5cd.png">

**Comment by 50Wliu** [comment]
Thanks for reporting!  I've removed that build status icon.

/cc @kevinsawicki since it was pointing to https://ci.appveyor.com/project/kevinsawicki/wrap-guide/branch/master
