### ISSUE TITLE
Vertical Line is not correctly placed for font Family changes 

### ISSUE THREAD

**Issue by boccaFF** [atom/wrap-guide#55]
When the Font Family is changed (e.g. Terminus), the line will not be update to reflect the adequate position. This seems similar to #25.

**Comment by lee-dohm** [comment]
This is essentially a duplicate (position of the guide is not changing for font changes in the Settings View). Please add this to #25 so it can be fixed at the same time.

**Comment by lee-dohm** [comment]
I went ahead and updated #25. You may want to subscribe there for updates. Thanks for catching this!
