### ISSUE TITLE
Wrap guide by language

### ISSUE THREAD

**Issue by nelson6e65** [atom/wrap-guide#59]
I use to code in many languages at the same time. And... Is annoying to set pref. line length when I switch between languages that uses different code style rules about this.

For example, PSR2 in PHP is set to 120, but CoffeeScript is 80.

It should be nice auto-set line length depending on current syntax.

**There is a way to achieve this in  Atom?**

**Comment by 50Wliu** [comment]
You can scope the `editor.preferredLineLength` setting.  http://flight-manual.atom.io/behind-atom/sections/scoped-settings-scopes-and-scope-descriptors/#scoped-settings-scopes-and-scope-descriptors

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
