### ISSUE TITLE
Wrap guide is at two different widths on two different files

### ISSUE THREAD

**Issue by JosephTLyons** [atom/wrap-guide#79]
I typically switch back and forth between 80 columns (when writing documentation) and 100 columns (when writing actual code).  I went to switch my setting back to 80 and noticed that it didn't change within a Rust file, but it changed inside a Markdown file I was working on.  In the Rust file, it is still at 100 columns, but it is correct in the Markdown file, at 80 columns.  Changing the values a few times back and forth, disabling / enabling Wrap Guide package, and exiting out of Atom and restarting, all did nothing to fix the issue.  Any help is greatly appreciated.

I'm on Atom 1.28.0, on macOS 10.13.5, and Wrap Guide 0.40.3.

**Comment by Arcanemagus** [comment]
Are you able to reproduce the problem in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? Can you provide exact steps to reproduce this?

Next time please use the template when filing an issue, thanks!

**Comment by JosephTLyons** [comment]
After more investigation, it seems that this is [related to `atom-rust-language` package.](https://github.com/zargony/atom-language-rust/issues/138)
