### ISSUE TITLE
Horizontal Line Stuck

### ISSUE THREAD

**Issue by scottwater** [atom/wrap-guide#9]
I recently started seeing a horizontal line that I cannot seem to get rid of.

Here is a screenshot: https://www.evernote.com/shard/s173/sh/aac301a4-f219-44ba-bd36-f87f828da7c0/f1de92db580b44260b899ab36a7f9992

It was [suggested](http://discuss.atom.io/t/horizontal-line-in-editor/2717) on the Atom forums to disable the wrap-guide and that seems to have fixed the issue.

**Comment by mkov88** [comment]
Total noob here,

I figured out where to add CSS.

How do you disable the `<wrap-guide>` package

**Comment by 50Wliu** [comment]
Open Settings through <kbd>Cmd+,</kbd> or <kbd>Ctrl+,</kbd>, then go to Packages, and search for "Wrap Guide".  There should be a "Disable" button there.

**Comment by mkov88** [comment]
Excellent! Thanks!
